### ISSUE TITLE
Is anyone seriously using this adapter for shutters ?

### ISSUE THREAD

**Issue by mghomedev** [Excodibur/ioBroker.tahoma#107]
I find this adapter to be totally erradicate / random in behavior. Sometimes it works, sometimes it doesnt. 

I reported already issues a while back e.g. in https://github.com/Excodibur/ioBroker.tahoma/issues/18 but even the latest version doesnt work reliably.

The worst thing is, when you close your shutter and then you _really_ need to stop because something is in the way (e.g. flowers or a child or a cat or whatever)  . And then it doesnt work. 

I am curious, if it really works for other people and you trust this adapter to be used...?

P.S.

I also have the original Tahoma app installed on my mobile phone and it works not perfect but at least the Stop-Button is somewhat more reliable

**Comment by DirtyAtze** [comment]
I'm using this Adapter since the release and I dont have any serious issues.
From time to time it loses connection an has to be stopped for about 5 minutes. After te restart it works perfectly again.
This problem appears about once a month and i dont know the reason.

I have 8 rs100 shutter motors, 2 blinds, 2 velux skylight shutters and 1 garage door drive. Besides I have a sun sensor and some temperature sensors. All with the io protocol.

But if there is a Child, Cat etc. in the way, i would simply use the wall switch to stop the suhtter instead of searching for my smartphone open the App/Vis or whatever and stop the shutter. Because I think the Cat would be dead before the App even started.

**Comment by mghomedev** [comment]
Thanks, It is good to hear that it works for some people.

**Comment by Master-Rudi** [comment]
Oh cat, be careful go away!! Oh wait I search my phone to stop the shutter… where did i put my phone yesterday… hmm ok there it is.
VIS is loading… ok cat  wait for it, I am gonna safe your life…
Ok stop the shutter… oh sorry cat… too late

For me the adapter works fine, but in any case of emergency-> don’t search your phone :)

i use it for an automated open and close of my shutters when the sun comes out or the temperature rises and I am not at home. At the evening when the sun is not as high and hot, the shutters open automatically for example.
I have also a door sensor which prevents the shutter on the door to get fully down when the door is open to prevent getting locked out when I am in the garden for example.
Just a few examples for what I use that adapter!


So just for automatic use, I still have and use the wall mounted switches…!

**Comment by Excodibur** [comment]
For me it works fine, too - apart from the occasional login issues.

I am looking into some improvement of command-handling in the adapter though. With 0.5.6, once you set a command to **true** to trigger it, it mostly stays **true**, even though the action behind it is already completed. The plan is to reset the command-state to **false**, once the action is finished, so that it better represents what is happening right now.

**Comment by Excodibur** [comment]
Please feel free to give [Release 0.6.0](https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.6.0) a try for improved _commands_ state-handling.

**Comment by nummerxiv** [comment]
Thank you very much for working on this adapter. Its the only way to handle Somfy shutters without that horrible app. 👍

**Comment by mcm1957** [comment]
Thanks for the adapter too.

Only possible improvment could be to reduce the number of identical error messages (- supress identical errors and add info as soon as tohoma web is working again -) to reduce number of entries in log.

**Comment by mghomedev** [comment]
Thanks alot all for your feedback!
I tried the latest version of the adapter recently, and it was still pretty much erradicate behavior i.e. sometimes it works correclty but suddenly a very long delay until it reacts and sometimes many seconds later it does "something" again. 

Anyways, there is a new local Somfy Tahoma API coming out, it should work better in future. I created this issue for that in future https://github.com/Excodibur/ioBroker.tahoma/issues/146
