### ISSUE TITLE
Error when trying to use local API

### ISSUE THREAD

**Issue by DirtyAtze** [Excodibur/ioBroker.tahoma#147]
I tryed using the local API for tahoma today, but it wont connect to the API. I tryed both w/ and wo/ MDNS.

I activated the developer mode on the Somfy homepage. Is there anything else i have to do to start using the local API?

iobroker log:

<html>
<body>

tahoma.0 | 2022-06-02 08:34:39.510 | warn | {"error":{"errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"gateway-XXXX-XXXX-XXXX"}}
-- | -- | -- | --
tahoma.0 | 2022-06-02 08:34:39.510 | warn | setup failed!
tahoma.0 | 2022-06-02 08:34:39.509 | warn | error during request: Error: getaddrinfo ENOTFOUND gateway-XXXX-XXXX-XXXX, request path: setup with payload:{}
tahoma.0 | 2022-06-02 08:34:39.436 | info | Using stored bearer token XXXXXXxxxxxxXXXXXxxxx
tahoma.0 | 2022-06-02 08:34:39.435 | info | Adapter will connect to Tahoma Box via local API.
tahoma.0 | 2022-06-02 08:34:39.434 | info | Configured polling interval: 20000
tahoma.0 | 2022-06-02 08:34:39.434 | info | [START] Starting adapter tahoma v0.7.1.3
tahoma.0 | 2022-06-02 08:34:39.346 | info | starting. Version 0.7.1 (non-npm: Excodibur/ioBroker.tahoma#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx) in /opt/iobroker/node_modules/iobroker.tahoma, node: v14.19.1, js-controller: 4.0.23

</body>
</html>

**Comment by DirtyAtze** [comment]
Looks like i am not the only one with this issue (issue #148).
Also it is not possible to switch back to cloud api, once local api was configured.
I had to uninstall and reinstall the adapter to get the cloud api connected again.

**Comment by Excodibur** [comment]
It looks like the DNS entry of your Tahoma box cannot be resolved. This is not a problem caused by the adapter itself, but by your local network infrastructure, or OS setup.

If available you could check via `nslookup gateway-XXXX-XXXXX-XXXX` if name-resolution works (on the machine where ioBroker and the adapter are running). If not, you could add an additional entry to your _hosts_ file so that local name resolution is used instead.

If you do not know, which IP your Tahoma locally has, apart from `nslookup` you could also look it up directly on your router which normally should have a full table of all devices connected to the network. This is e.g. how it looks for a Fritz.Box:
![image](https://user-images.githubusercontent.com/70700967/172308022-4b71d37c-b0fc-457c-a4df-dff099d79ca4.png)

Also: Once you empty the gateway PIN field (_PIN of the Tahoma box_) the adapter should attempt to connect to the online Tahoma API again after restart.

**Comment by DirtyAtze** [comment]
Thank you very much! I renamed the TaHoma Box in my FritzBox (for better indentification). 
now I added an DNS Record and it works just fine!

But if i delete the DNS Record and empty the PIN-Field of the adapter, the adapter doesnt connect to the cloud API. The log shows this:

<html>
<body>


tahoma.0 | 2022-06-07 08:50:58.063 | warn | error during request: ->401 retry setup
-- | -- | -- | --
tahoma.0 | 2022-06-07 08:50:58.062 | warn | error during request: ->401 retry actionGroups
tahoma.0 | 2022-06-07 08:50:57.940 | info | Using stored bearer token XXXXxxxxXXXXxxxx
tahoma.0 | 2022-06-07 08:50:48.064 | info | Login failed 3 times, waiting 380 seconds before retrying.
tahoma.0 | 2022-06-07 08:50:48.064 | warn | error during request: ->401 retry setup
tahoma.0 | 2022-06-07 08:50:48.063 | warn | error during request: ->401 retry actionGroups
tahoma.0 | 2022-06-07 08:50:47.938 | info | Using stored bearer token XXXXxxxxXXXXxxxx
tahoma.0 | 2022-06-07 08:50:38.130 | warn | error during request: ->401 retry actionGroups
tahoma.0 | 2022-06-07 08:50:38.129 | warn | error during request: ->401 retry setup
tahoma.0 | 2022-06-07 08:50:37.938 | info | Using stored bearer token XXXXxxxxXXXXxxxx
tahoma.0 | 2022-06-07 08:50:37.936 | info | Configured polling interval: 20000
tahoma.0 | 2022-06-07 08:50:37.935 | info | [START] Starting adapter tahoma v0.7.1.3
tahoma.0 | 2022-06-07 08:50:37.922 | info | starting. Version 0.7.1 (non-npm: Excodibur/ioBroker.tahoma#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx) in /opt/iobroker/node_modules/iobroker.tahoma, node: v14.19.1, js-controller: 4.0.23


</body>
</html>

But i think this problem is an seperate issue, so we can close this one.
