### ISSUE TITLE
old ip adress can´t be changed / deleted

### ISSUE THREAD

**Issue by Randy1st** [Excodibur/ioBroker.tahoma#172]
Recently had to change the ip adress of my tahoma premium box.
according to the protocoll the adapter still searches for the old ip ... i deleted instance and adapter and also every single on my server file called *tahoma*... i used another instance nr... nothing changes. 
How can I reset the ip adress?

**Comment by Excodibur** [comment]
That sounds weird. Usually deleting the adapter should also get rid of any config for it, I think.

Did you also try to activate Expert-mode (
![image](https://user-images.githubusercontent.com/70700967/197563360-c6b04c51-4a3c-4d4b-958a-7af19bebe89d.png)
) in ioBroker admin and delete the whole `/system/adapter/tahoma` folder, in case it still exists after adapter adapter-deletion?

**Comment by Randy1st** [comment]
I actually don´t know where to find this folder called adapter (ioBroker runs in docker on a synology nas) but I deleted everything called tahoma in my iobroker docker folder

Even in expert mode there´s no such folder in ioBroker

**Comment by Excodibur** [comment]
You can only find this in the Admin GUI, see here:
![image](https://user-images.githubusercontent.com/70700967/197625323-6438e5d4-c1ae-48b3-8868-1e8194c40dc0.png)

If there is no folder below `/system/adapter` (which always exists), then there should be no config for that adapter left in iobroker after removing it.

**Comment by Randy1st** [comment]
thanks a lot  :-) folder system found. No Tahoma Adapter folder in there.

I now reinstalled the tahoma adapter, deleted the "system/adapter tahoma folder" deleted then the tahoma adapter,
rebooted iobroker, reinstalled the Tahoma Adapter... nothing changes.. 
The old ip adress must be captured somewhere. MDNS doesn´t work too (mdns is activated in unifi - maybe docker is the problem here)

log shows my old ip address 
![image](https://user-images.githubusercontent.com/109476751/197695205-cf98bce4-7bb5-4722-a0d4-2e13e65d62f7.png)

**Comment by Excodibur** [comment]
Just to be clear, do you configure the new IP-address directly in the adapter and that gets ignored, or do you continue to use the hostname there? I also run iobroker as container and MDNS does not work for me, although I thought it might be related to my Fritz-Box router.

If you configure the hostname, it would be helpful to know if the resolution for the new IP address on the host system (so outside of the docker container) works properly, e.g. by running `nslookup <hostname>`. Perhaps the dns-cache is outdated there.

**Comment by Randy1st** [comment]
the tahoma box got a new ip address  - iobroker ip wasn´t changed
I don´t configure any ip addresses in the adapter the tahoma adapter searches for the tahoma pin - 
the resolution of the tahoma box pin is not working - protocol shows that the adapter still searches for the outdated ip address of the tahoma box.

sorry if I misunderstood your question

**Comment by Excodibur** [comment]
Sorry for the confusion.

The question is how your host system, meaning the OS iobroker/docker container are running on resolves the hostname. The Tahoma-Adapter itself does not resolve the hostname of the Tahoma-Box, it just bascially tells your host-system "hey I am looking for the IP of the host `gateway-<gateway-pin>` or `gateway-<gateway-pin>.local` (if mdns is used) in the current network. Your host-system gets that information from the configured DNS-server, which is usually your router (e.g. FritzBox/Speedport, etc). 

If the adapter still tries to connect to the wrong IP, then it is because some factor outside of your iobroker-setup resolves the hostname wrongly.

There are multiple possible root causes for this:

- Your router advertises the wrong IP for the Tahomabox hostname to your host-system (here: diskstation). --> This is unlikely.
- Your /etc/hosts file contains an outdated hostname-IP mapping for the Tahomabox. --> As you would have to have added this entry manually by yourself at some point, I assume this is also not the case.
- Your diskstation has an outdated entry in its DNS-cache, which for the Tahomabox hostname still points to the wrong IP. To force a client-side DNS cache flush on the diskstation they easiest way I know of would be to reboot it.

**Comment by Randy1st** [comment]
thanks a lot, really appreciate the time you spend here.

your assumption is right I didn´t change the mapping manually 
the unifi USG shouldn´t advertise a wrong IP so it might be some kind of DNS cache issue

unfortunately rebooting the whole system with any components wasn´t the solution.  

I will check all the dns settings of the systems and maybe set up a new iobroker session for testing to see if the resolution works then.
Thanks a lot

**Comment by Randy1st** [comment]
I created another iobroker-installation - same issue. 
with no doubt the adapter isn´t responsible for this problem.

Thanks so much for your help, I will close the issue
