### ISSUE TITLE
15 second error-retry delay is way too high in processApplyQueue when sending command fails

### ISSUE THREAD

**Issue by mghomedev** [Excodibur/ioBroker.tahoma#18]
In processApplyQueue there is a constant of 15000ms such that in case of errors, i.e. it tries again to send a command after 15 seconds.

This is way too high (imagine that a simple user presses a button to open or close a shutter or dor, it doesnt work, he goes away and suddenly after 15 seconds it starts to move).

I strongly suggest to reduce that to at most like 1 seconds or 1.5 seconds, and if it fails again, discard the whole queue.

**Comment by mghomedev** [comment]
P.S.

These cases of retries should also be logged with "warn"

**Comment by mariusbach** [comment]
@mghomedev it's here: https://github.com/StrathCole/ioBroker.tahoma/blob/0ce0d308c67d50744bd382528389fb2bac7f3d44/lib/tahoma.js#L1273

can you change it and test it and report back? I'm wondering what happens if you try to move a bunch of shutters (I have 9) at the same time. mine start 1-2s one after another and the whole sequence might just fit into 15s; so what happens if the timer times out and not all shutters actually have been commanded yet?

**Comment by mghomedev** [comment]
I already reduced it in February from 15000 to 1500 (i.e. from 15 seconds to 1.5seconds) . Only after that it was reasonable to use in iobroker for me. However, I only have two shutters and so I would probably not run into the problem that you described.
Maybe you make the value configurable by a settings for normal users?

**Comment by Excodibur** [comment]
I fixed it now in the Github repo , and will include it in the next adapter release. 15 seconds definitely is too high. I set it to 1,5 seconds as suggested, but if you use Admin 5, you can also set a custom value in the adapter configuration dialog now. ;-)

For my point of view the amount of shutters that might be affected by the commands send to the apply queue don't matter here. `setTimeout` contrary to its name does not set a timeout for `processApplyQueue`, it just delays the execution of that command for the configured amount of time. The function `processApplyQueue` then takes as long as it needs due to the asynchronus nature of NodeJS.

**Comment by StrathCole** [comment]
The reason I set the value that high is:
If somfy does maintenance and you get 400/503 error it is mostly not working on retry after only 1 or 2 seconds. Although under some circumstances it could lead to too fast retries which might trigger a rate-limit. As the adapter does not use an official API, the rate-limiting is a full black box.

**Comment by Excodibur** [comment]
Ok, I see that it might not work right after 2 seconds, but since it is just tried once more ("secondtry") I would assume that Tahoma doesn't start rate-limiting right away. But you are right, we can't know for sure.

It can still be changed via configuration by the user and if we see an increase in issues we could take another look at it, I think. Waiting for 15 seconds for commands that are expected to have an immediate effect seems a bit too spooky for me on the other hand. :-)
