### ISSUE TITLE
regular warning "too many asynchronous jobs"

### ISSUE THREAD

**Issue by Kaiman77** [Excodibur/ioBroker.tahoma#206]
The adapter throws a regular warning (roughly speaking every morning around 8:00) and needs about 5 minutes to get a new eventRegisterID.

In those 5 minutes, the adapter is not usable of course.

![grafik](https://user-images.githubusercontent.com/47158634/216537467-5f63c072-35ee-42e4-91d2-a14005eb5ba3.png)

**Comment by Excodibur** [comment]
Are you using any other adapter that controls the devices during that time, perhaps Shuttercontrol for blinds? If I remember correctly, if there is a very short delay  set there between triggering a state-change for the devices it might result in a lot of jobs hitting the Somfy API in short order, which is why generally the adapter tries to group requests with less than 500 ms delay into one job. 

If lets say you have a delay of 1-2 seconds between triggering a state-change for each device, the adapter can't "group" this into one job and will try to run multiple jobs in short sequence against the Somfy API, which might result in that error coming from their servers.

**Comment by Kaiman77** [comment]
Hi - no, there are only a few scripts triggering Tahoma devices. And since I only have two awnings there haven't been any device triggers within the last months (it's winter ;-) ). The error appear more or less once a day, sometimes twice, sometimes every few days. But it definitely doesn't go along with any device usage.

**Comment by Kaiman77** [comment]
The issue doesn't appear on my system anymore - I must admit that I'm not sure why. But it doesn't happen with version 0.10.0 through 0.10.2

**Comment by Excodibur** [comment]
Ok, let's close the issue for now. We can reopen it, in case it happens again.
