### ISSUE TITLE
error during tahomalink request: undefined ->401 retry login

### ISSUE THREAD

**Issue by uwe72** [Excodibur/ioBroker.tahoma#21]
Cannot login, see error code in the subject.

When i use the same user and password i am able to login to 
https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/

**Comment by uwe72** [comment]
after a while the error dissappeared.....anyhow strange.

**Comment by andy6325** [comment]
Same error on my side. Usually, I solve the problem by stoping the adapter and starting it after a few hours again. 

In the log I see: 
tahoma.0 | 2021-04-06 07:04:55.582 | info | (9483) Login failed three times, waiting 2 minutes before retrying.
tahoma.0 | 2021-04-06 07:04:55.582 | warn | (9483) error during tahomalink request: undefined ->401 retry login (5 times)

Is it possible to decrease the number of logins from 5 to 3 and to set the waiting time to a longer period? I assume that the IP Address is getting blocked for some time.

**Comment by SaschaS87** [comment]
Same problem with me. It always occurs sporadically.

Beside the above error messages I get an error message before.

2021-03-22 07:00:24.203 - tahoma.0 (24844) refresh device state failed
2021-03-22 07:00:48.128 - tahoma.0 (24844) error during tahomalink request: undefined ->401 retry login
2021-03-22 07:00:48.218 - tahoma.0 (24844) error during tahomalink request: undefined ->401 retry login
2021-03-22 07:00:58.361 - tahoma.0 (24844) error during tahomalink request: undefined ->401 retry login

**Comment by MichaelSchaaf999** [comment]
same problem with me: 
(25759) error during tahomalink request: undefined ->401 retry login
and
info | (3790) Login failed three times, waiting 2 minutes before retrying.
warn | (3790) error during tahomalink request: undefined ->401 retry login
So: Commands are not forwarded to Tahoma at all, as the login fails due to too many login requests.
What will we do to remedy this?

**Comment by danimeierch** [comment]
Same problem here..... I hope, you can fix it! Thanks a lot!

**Comment by uwe72** [comment]
if i am the owner of an adapter i take care or i give it up at all. hard for me to understand how it is possible to let wait so many users. sorry for my opinion.

**Comment by StrathCole** [comment]
> or i give it up at all.

Just as you wish. Abandoned from now on.

**Comment by uwe72** [comment]
there is no difference. at least we know it

**Comment by MichaelSchaaf999** [comment]
This issue is closed now?

I have the current messages in the logfile...


tahoma.0 | 2021-04-27 13:57:52.006 | warn | (923) Body: {"errorCode":"UNSPECIFIED_ERROR","error":"No registered event listener"}
-- | -- | -- | --
tahoma.0 | 2021-04-27 13:57:52.006 | warn | (923) Response: {"statusCode":400,"body":{"errorCode":"UNSPECIFIED_ERROR","error":"No registered event listener"},"headers":{"date":"Tue, 27 Apr 2021 11:57:51 GMT","server":"overkiz","strict-transpor
tahoma.0 | 2021-04-27 13:57:52.006 | warn | (923) error during tahomalink request: null, request path: events/b0beb1f9-ac10-3401-3873-80aeab51ce3f/fetch with payload:{}
tahoma.0 | 2021-04-27 13:57:51.085 | error | (923) Cannot find search "folder" in "system"
tahoma.0 | 2021-04-27 13:57:51.085 | error | (923) Cannot find search "folder" in "system"
tahoma.0 | 2021-04-27 13:57:51.083 | error | (923) Cannot find search "folder" in "system"
tahoma.0 | 2021-04-27 13:57:51.082 | error | (923) Cannot find search "folder" in "system"
tahoma.0 | 2021-04-27 13:57:49.966 | warn | (923) error during tahomalink request: undefined ->401 retry events/b0beb1f9-ac10-3401-3873-80aeab51ce3f/fetch
tahoma.0 | 2021-04-27 13:57:49.953 | warn | (923) error during tahomalink request: undefined ->401 retry /setup/devices/states/refresh

What can I do about it?
