### ISSUE TITLE
maybe - See moving - fail

### ISSUE THREAD

**Issue by Jumbo125** [Excodibur/ioBroker.tahoma#226]
Hello
Thank you for your great work.
I would like see when the roller blind is moving.

If i change the core:ClosureState , the blind moves but the states.core:MovingState is always "false".  Is there any state how shows me, if the blind moves at this moment?
Thank you

**Comment by Jumbo125** [comment]
i try to understand the code
can you tell me how i can get a token for the https://www.tahomalink.com/enduser-mobile-web/enduserAPI/

to open it in my brwoser and show what i`m get

**Comment by Excodibur** [comment]
Hi,

If you want to login to this programatically by yourself, you need to send a POST-request to the `/login` endpoint and provide the fields `userId` and `userPassword` in the request body. The endpoint should return a JSESSIONID cookie (header field `Set-Cookie` in the response) that you can use to authenticate for further requests. Simply opening the endpoint in your Browser won't help, since you need a client that is able to send REST requests (e.g. curl, or Postman) to setup the POST-request to that endpoint correctly.

Regarding the status being not updated correctly, does the behaviour change, if you use `core:TargetClosureState` instead to steer the blinds? If the issue persists, please provide some DEBUG-logs of the adapter so I can check it further.
