### ISSUE TITLE
Is the new TaHoma Switch supported?

### ISSUE THREAD

**Issue by flotux2** [Excodibur/ioBroker.tahoma#43]
Hi,

I'm planning to integrate my Somfy shutter control into ioBroker. Is the new TaHoma Switch supported by your adapter? Or is only the TaHoma Premium box supported?

I checked the following sheet that compares the compatibility of TaHoma Switch, TaHoma DIN Rail and TaHoma Premium. 
According to this table the local API is also supported in the new TaHoma Switch. I assume your adapter is using this API for access?
![Tahoma](https://user-images.githubusercontent.com/23209679/133456526-96d30824-4c6d-47fd-bbf3-2f563df2f859.png)

Any hint is appreciated so that I do not buy the wrong box. ;-)

Kind regards
Florian

**Comment by Excodibur** [comment]
The most honest answer about Tahoma Switch support I can give is "I don't know". Mainly because I only own Tahoma Premium and therefore cannot test it myself. If it can be controlled via Tahomalink.com or the Tahoma Smartphone app, I would say there is a good chance it could work, since they use the same API that this adapter uses (in an unofficial manner). I don't know though if the API differs for Tahoma 3.0 vs. 2.0.

The "Local API" seems not much more than some rumor spread by Somfy, but I know of numerous cases where people asked Somfy about more information and did not get any meaningful reply. To me it seems like Somfy has no real interest to provide a  solution for offline access of their device-API, which is a shame. Closing down their forum where customers at least could exchange directly about such topics does not make things easier either. :-(

The only real offline/local API that exists for Somfy IO devices to my knowledge is offered via Velux KLF 200, but I don't own that one either.

**Comment by flotux2** [comment]
@Excodibur 
Thanks for your detailed answer. I will therefore play it safe and buy the Tahoma Premium box.
