### ISSUE TITLE
Login failed - Retry only possible when adapter is offline for a long time.

### ISSUE THREAD

**Issue by svenover** [Excodibur/ioBroker.tahoma#69]
Irregularly but filled too often, the Tahoma adapter can no longer connect with.

Then the log says that the login was not successful and a new login will be tried.

If I then take the adapter offline for a longer time and restart it after this time, it can log in again and the listener is registered.

I have also already set the time that the adapter should fetch the data from Tahoma to 0.

I do not need any status from the Tahoma box. I only want to send commands. And for that I am indebted to the greatest thanks. Totally ingenious.

Please let me know, if I do something wrong or check the issue and let me know, what I have to do.

Many thanks in advance.
Sven

**Comment by Excodibur** [comment]
If you mean you set the _polling interval_ to 0, then the adapter will set it to 5 seconds by default, since you shouldn't use lower values than that. You can also not fully deactivate polling for new data since this is the core-mechanic of this adapter. To avoid the Tahoma-account to get locked it is even better to set the polling rate much higher, so the Somfy-servers are queried less often for new metrics and therefore are less likely to mistake your queries as some form of attack to the system. Commands will still be executed immediately.

In this particular instance your account was likely temporarily locked, but as you saw it usually gets unlocked after deactivating the adapter for a few hours/days. 

Recently my account got locked temporarily, too, but I think the root cause was a downtime of the Tahomalink servers. On 08.12. the Tahomalink servers returned the following message:
```
Server is down for maintenance
\n
\n We are sorry for the inconvenience.
\n Please try again in a few minute
``` 
Since the adapter uses an inofficial API here, it is hard to predict what messages Somfy servers will send in that case. Currently the adapter simply does not recognize such server error responses and tries to login anyways. I guess this could lead to some form of temporary account locking on Somfy's side as well.

I'll check if the adapter can at least be improved to adjust its login pattern to such downtime-errors - perhaps wait half a day before attempting another login, or something.

**Comment by svenover** [comment]
Hi,

I have changed the value to 24hours. 

Your idea to catch a possible maintenance is a very good idea.

Many thanks for your support.
