### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by AC411** [Excodibur/ioBroker.tahoma#9]
Hi,

i recently updated my raspberry pi and my iobroker. The Adapter is still green, but connection fails. 
Does anybody have the same issue? Any ideas?

Best regards
Alexander

**Comment by Markus-GH** [comment]
Hello,

i have the same problem. Since I updated the system the adapter doesn't work. The adapter is green but there is no way to operate the shutters.

Node.js v.12.18.3
npm 6.14.6
Adpater version 0.3.2

Can somebody help here? I'm pretty new at this.

Update to Version 0.3.3?

Thanks for help
Best regards
Markus

**Comment by Raabensohn** [comment]
same here...

`

tahoma.0 | 2020-09-21 22:33:29.345 | warn | (27254) error during tahomalink request: undefined ->401 retry login
-- | -- | -- | --
tahoma.0 | 2020-09-21 22:33:29.220 | debug | (27254) POST request on https://www.tahomalink.com/enduser-mobile-web/enduserAPI/login with payload: +++redacted+++

`

**Comment by StrathCole** [comment]
Please stop the adapter and wait for some hours before you re-enable it. Mostly this is due to rate-limiting by tahoma.

**Comment by Raabensohn** [comment]
thx... will try.

**Comment by StrathCole** [comment]
> thx... will try.

If it works again after that, please try increasing the poll interval.

**Comment by Raabensohn** [comment]
> Please stop the adapter and wait for some hours before you re-enable it. Mostly this is due to rate-limiting by tahoma.

I waited 2 days... and changed poll to 50000.
same issue... :-(

**Comment by Raabensohn** [comment]
und plötzlich geht es wieder.... warum auch immer...

**Comment by Markus-GH** [comment]
> 
> 
> Please stop the adapter and wait for some hours before you re-enable it. Mostly this is due to rate-limiting by tahoma.

I did it the same way. Now it works again. Thanks a lot.

**Comment by hmpft** [comment]
Anyone else getting login errors with this plugin / at tahomalink.com ?

**Comment by Raabensohn** [comment]
me.
What do you suggest as poll interval?

**Comment by hmpft** [comment]
I called Somfy. Turns out I have a Connexoon box and not a Tahoma box. The fact that the API worked perfectly with the Connexxoon for a few months was probably a mistake. The employee did not want to unlock my account.

**Comment by Raabensohn** [comment]
I have a tahoma box. sometimes it works, sometimes it doesn't! :-(

**Comment by Moormerlander** [comment]
Seems this adapter or api is very unreliable....

**Comment by DirtyAtze** [comment]
I have this Adapter running since it was released and never had a problem.
So i dont think it is a problem of the adapter.

**Comment by Raabensohn** [comment]
it worked for me as well for a very long time...
then suddenly (no changes made) it started to alternate between working and not working...
what could be the problem if not an unstable adapter?
I don't doubt that it was really good for a long time, as I said, it worked for me too...
But maybe somfy changed something in the api and now the adapter need adjusting...

**Comment by StrathCole** [comment]
The problem in most cases is a rate-limiting in the API. When that hits, the adapter will get 401-errors which it currently does not handle very well. Mostly it helps when you increase the polling time and wait a few minutes until you re-enable the adapter.

**Comment by Raabensohn** [comment]
as asked above: what is a decent polling time?

**Comment by StrathCole** [comment]
> as asked above: what is a decent polling time?

I guess that highly depends on the amount of shutters, count of commands and also commands sent from different sources than ioBroker. I have set it to 30000 now as 10000 gave me error 401 some times.

**Comment by Raabensohn** [comment]
> > as asked above: what is a decent polling time?
> 
> I guess that highly depends on the amount of shutters, count of commands and also commands sent from different sources than ioBroker. I have set it to 30000 now as 10000 gave me error 401 some times.

Okay, I'll try how that works... ;-) I had 10000 aswell...

**Comment by Excodibur** [comment]
Is see the main problem here with Somfy. There is no official information from their side under which circumstances they start to enforce rate-limiting for requests or termporarily lock user accounts due to failed logins. Even the unlocking process seems broken/unreliable on their side, as it does not seem to take effect immediately. Perhaps they do this for some security-purpose, but as it is not documented, it is annoying.

I would close this ticket for now as there is no apparent task I can take for the adapter from this, but please feel free to open a new issues, if you experience problems again. The "undefined" error message mentioned above is fixed with v0.4.0 at least. :-)
